name: bpmanv_app_sharedFiles
description: This package provides functionality shared across both the trainee and trainer App of the digital dPS.
version: 0.0.8
author:
homepage:
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  font_awesome_flutter: ^9.0.0
  intl:
  http: ^0.13.1
  shared_preferences: ^2.0.5
  freezed_annotation: ^0.14.1
  json_serializable: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.12.2
  freezed: ^0.14.1+1
  import_sorter: ^4.4.3

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  assets:
    - assets/icons/bleeding_icon.png
    - assets/icons/critical_bleeding_icon.png
    - assets/icons/fracture_icon.png
    - assets/dead.png