name: dps.training_shared_files
description: This package provides functionality shared across both the trainee and trainer App of the digital dPS.
version: 0.0.12
publish_to: none


environment:
  sdk: ">=2.19.2 <3.0.0"
  flutter: ">=3.7.5"


dependencies:
  # flutter specific dependencies
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any

  # general dependencies
  dio: ^5.0.2
  web_socket_channel: ^2.3.0
  shared_preferences: ^2.0.18
  json_annotation: ^4.8.0
  freezed_annotation: ^2.2.0
  font_awesome_flutter: ^10.4.0

  

dev_dependencies:
  # flutter specific dependencies
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.3

  # general dependencies
  json_serializable: ^6.6.1
  freezed: ^2.3.2
  flutter_lints: ^2.0.1
  import_sorter: ^4.6.0


# The following section is specific to Flutter.
flutter:
  assets:
    - assets/icons/bleeding_icon.png
    - assets/icons/critical_bleeding_icon.png
    - assets/icons/fracture_icon.png
    - assets/dead.png
    