name: Continuous Integration

on:
  push:
    branches:
      - dev
  pull_request:
    branches: [ master, dev ]
  
jobs:
  build:
    # This job will run on ubuntu virtual machine
    runs-on: self-hosted
    timeout-minutes: 8
    steps:

    # Setup the git environment
    - uses: actions/checkout@v3

    # Setup the java environment
    - uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '11'
    
    # Setup the flutter environment.
    - uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
    
    # print flutter version for debugging/documentation
    - name: Flutter version
      run: flutter --version
    
    # Get flutter dependencies.
    - name: Get dependencies
      run: flutter pub get
    
    # Statically analyze the Dart code for any errors.
    - name: Statically analyze flutter code
      continue-on-error: true
      run: flutter analyze .